# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://blorente.github.io/
baseurl: http://blorente.github.io/
title: Borja Lorente
author: Borja Lorente
description: Personal blog and portfolio
avatar: profile_med.jpg
email: blorente@ucm.es
github: blorente
twitter: BLorenteEs
linkedin: https://www.linkedin.com/in/blorente
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
