# Site settings
title: "BORJA LORENTE"
email: blorente.me@gmail.com
description: "Blog and Portfolio of Borja Lorente Escobar"
baseurl: ""
url: "http://blorente.me/"
title_description: "Software Engineer and Programming Language enthusiast.\nI love making the lives of my fellow programmers easier. Check out some of my <a href=\"{{ site.baseurl }}/portfolio\">projects!</a>"
title_image: "https://pbs.twimg.com/profile_images/1155229690992500736/P_aQccar_400x400.jpg"
google_analytics: "UA-153119910-1"
disqus_account: blorente-me
github_repository: https://github.com/blorente/blorente.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: BLorenteEs
github_username:  blorente
#instagram_username: 
#reddit_username: 
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
#xing_link:
#facebook_link:

# Footer
footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
